datasource:
  url: jdbc:postgresql://localhost:5433/hibernate
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: postgres
hibernate:
  show-sql: true
  dialect: org.hibernate.dialect.PostgreSQLDialect
liquibase:
  enabled: true
  change-log: classpath:db/changelog/changelog-master.yml