spring:
  application:
    name: motor_show
  datasource:
    url: jdbc:postgresql://localhost:5433/hibernate
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
  logging:
    level:
      root: info
      ru.clevertec.motor_show: debug